// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    1: typeof import('./components/X6/1.vue')['default']
    AlgoNode: typeof import('./components/flow/components/AlgoNode.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    Flow: typeof import('./components/flow/index.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IconEpCheck: typeof import('~icons/ep/check')['default']
    IconEpEdit: typeof import('~icons/ep/edit')['default']
    IconEpPlus: typeof import('~icons/ep/plus')['default']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    NodesBar: typeof import('./components/X6/components/NodesBar.vue')['default']
    PanelArea: typeof import('./components/X6/components/PanelArea.vue')['default']
    PdfDemo: typeof import('./components/pdfDemo.vue')['default']
    Seamless: typeof import('./components/seamless.vue')['default']
    SpeakText: typeof import('./components/speakText.vue')['default']
    SvgIcon: typeof import('./components/X6/components/SvgIcon.vue')['default']
    Tabs: typeof import('./components/X6/components/Tabs.vue')['default']
    Toolbar: typeof import('./components/X6/components/Toolbar/index.vue')['default']
    VueNode: typeof import('./components/X6/shape/VueNode.vue')['default']
    VueStaticNode: typeof import('./components/X6/components/vue-static-shape/VueStaticNode.vue')['default']
    X6: typeof import('./components/X6/index.vue')['default']
  }
}
